name: Go CI

on:
  workflow_call:

env:
  GO_VERSION: '1.20'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: v1.52.2

  go_mod_tidy_check:
    name: Go Mod Tidy Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: go mod tidy

      - name: check for diff
        run: git diff --exit-code

  test_coverage:
    name: Unit Tests Coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Test & Coverage
        run: make cover
      - uses: codecov/codecov-action@v3.1.3
        with:
          file: ./coverage.txt

  unit_race_test:
    name: Run Unit Tests with Race Detector
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: execute test run
        run: make test-unit-race

  integration_test:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Swamp Tests
        run: make test-swamp

      - name: Swamp Tests with Race Detector
        run: make test-swamp-race
